# Site settings
title: How to Meet WCAG 2 (クイックリファレンス)
email: ee@w3.org
description: ""
baseurl: "/wai-wcag-quickref/" # the subpath of your site, e.g. /blog/
# baseurl: "/WAI/WCAG20/quickref/" # For publication
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: yatil
github_username:  yatil
status: release # draft
version: "2.5"

techniqueurl: http://waic.jp/docs/WCAG-TECHS/

port: 4099

safe: true
lsi: false

# Build settings
markdown: kramdown

gems: ['jekyll-github-metadata']
repository: 'w3c/wai-wcag-quickref'

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  blanklines: false
  profile: false

collections:
  filters:
    output: false
  help:
    output: false

exclude:
  - node_modules
  - .sass-cache
  - Gemfile.lock
  - Gemfile
  - gulpfile.js
  - npm-debug.log
  - package.json
  - questions.md
